name: Prepare New Release

on:
  push:
    branches:
      - main


jobs:
  version_and_release:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
    - name: "‚úîÔ∏è Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: ‚öô Run Tests
      uses: croconut/godot-tester@v2.5
      with:
        version: 3.4
        # should be long enough for asset import files to get generated
        import-time: 90
        assert-check: true
        max-fails: 0
        # How long the test should be run before it's timed out and fails
        test-timeout: 900
        # Directory containing Gut tests
        direct-scene: tests/cli/tests.tscn
    - name: "üì£ Release on push"
      id: release
      uses: rymndhng/release-on-push-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        bump_version_scheme: norelease
        use_github_release_notes: true
      # Always include the checkout step so that
      # your project is available for Godot to export
    - name: "‚úèÔ∏è Generate release changelog"
      if: ${{ steps.release.outputs.version != '' }}
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: "üíæ Commit new version"
      if: ${{ steps.release.outputs.version != '' }}
      run: |
          sed -i 's/GAME_VERSION := ".*"/GAME_VERSION := "${{ steps.release.outputs.version }}"/g' ./src/dreamscape/CFConst.gd
          sed -i 's/Therapy through Nightmares \[.*\]/Therapy through Nightmares [${{ steps.release.outputs.version }}]/g' README.md
          git config user.email github-actions@github.com
          git config user.name github-actions
          git commit -am 'version incremented'
          git push
    - name: "üõ† Randomize which html music will be exported"
      if: ${{ steps.release.outputs.version != '' }}
      shell: bash
      run: |
          SCENE=ordeal;  KEEP=6; cd assets/music/${SCENE}          && ls *.ogg | tail -n+${KEEP} | shuf > oggs && cat oggs | xargs -I {} mv "{}" "html_ignore_{}" && cat oggs | xargs -I {} sed -i 's/{}/html_ignore_{}/g' "{}.import" && cat oggs | xargs -I {} sed -i "s|[a-z0-9]\+\.oggstr|$(sh -c 'echo -n html_ignore_{} | md5sum  | awk "{print \$1}"').oggstr|g" "{}.import" && cat oggs | xargs -I {} mv "{}.import" "html_ignore_{}.import" && rm oggs && ls -larth
          SCENE=journal; KEEP=4; cd ../../../assets/music/${SCENE} && ls *.ogg | tail -n+${KEEP} | shuf > oggs && cat oggs | xargs -I {} mv "{}" "html_ignore_{}" && cat oggs | xargs -I {} sed -i 's/{}/html_ignore_{}/g' "{}.import" && cat oggs | xargs -I {} sed -i "s|[a-z0-9]\+\.oggstr|$(sh -c 'echo -n html_ignore_{} | md5sum  | awk "{print \$1}"').oggstr|g" "{}.import" && cat oggs | xargs -I {} mv "{}.import" "html_ignore_{}.import" && rm oggs && ls -larth
          SCENE=main;    KEEP=2; cd ../../../assets/music/${SCENE} && ls *.ogg | tail -n+${KEEP} | shuf > oggs && cat oggs | xargs -I {} mv "{}" "html_ignore_{}" && cat oggs | xargs -I {} sed -i 's/{}/html_ignore_{}/g' "{}.import" && cat oggs | xargs -I {} sed -i "s|[a-z0-9]\+\.oggstr|$(sh -c 'echo -n html_ignore_{} | md5sum  | awk "{print \$1}"').oggstr|g" "{}.import" && cat oggs | xargs -I {} mv "{}.import" "html_ignore_{}.import" && rm oggs && ls -larth
          SCENE=shop;    KEEP=2; cd ../../../assets/music/${SCENE} && ls *.ogg | tail -n+${KEEP} | shuf > oggs && cat oggs | xargs -I {} mv "{}" "html_ignore_{}" && cat oggs | xargs -I {} sed -i 's/{}/html_ignore_{}/g' "{}.import" && cat oggs | xargs -I {} sed -i "s|[a-z0-9]\+\.oggstr|$(sh -c 'echo -n html_ignore_{} | md5sum  | awk "{print \$1}"').oggstr|g" "{}.import" && cat oggs | xargs -I {} mv "{}.import" "html_ignore_{}.import" && rm oggs && ls -larth
          SCENE=boss;    KEEP=4; cd ../../../assets/music/${SCENE} && ls *.ogg | tail -n+${KEEP} | shuf > oggs && cat oggs | xargs -I {} mv "{}" "html_ignore_{}" && cat oggs | xargs -I {} sed -i 's/{}/html_ignore_{}/g' "{}.import" && cat oggs | xargs -I {} sed -i "s|[a-z0-9]\+\.oggstr|$(sh -c 'echo -n html_ignore_{} | md5sum  | awk "{print \$1}"').oggstr|g" "{}.import" && cat oggs | xargs -I {} mv "{}.import" "html_ignore_{}.import" && rm oggs && ls -larth
    - name: "ü§ñ Export game"
      if: ${{ steps.release.outputs.version != '' }}
      uses: firebelley/godot-export@v3.0.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4/Godot_v3.4-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4/Godot_v3.4-stable_export_templates.tpz
        relative_project_path: ./
        base_version: "${{ steps.release.outputs.version }}"
        create_release: false
        archive_export_output: true
        export_debug: true
    - name: "üõ† Prepare files for upload to itch.io"
      if: ${{ steps.release.outputs.version != '' }}
      shell: bash
      run: |
          cp -v /home/runner/.local/share/godot/dist/* .
          cp '/home/runner/.local/share/godot/builds/LinuxX11/Hypnagonia_Linux.x86_64' .
          cp '/home/runner/.local/share/godot/builds/Windows Desktop/Hypnagonia_Windows.exe' .
          cp '/home/runner/.local/share/godot/builds/Mac OSX/Hypnagonia_MacOSX.zip' .
          ls -larth
    - name: "üöÄ Upload HTML5 version to itch.io"
      if: ${{ steps.release.outputs.version != '' }}
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: "${{ secrets.BUTLER_CREDENTIALS }}"
        CHANNEL: HTML5
        ITCH_GAME: hypnagonia
        ITCH_USER: dbzer0
        PACKAGE: HTML5.zip
        VERSION: "${{ steps.release.outputs.version }}"
    - name: "‚ò¢ Upload Windows version to itch.io"
      if: ${{ steps.release.outputs.version != '' }}
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: "${{ secrets.BUTLER_CREDENTIALS }}"
        CHANNEL: windows
        ITCH_GAME: hypnagonia
        ITCH_USER: dbzer0
        PACKAGE: Hypnagonia_Windows.exe
        VERSION: "${{ steps.release.outputs.version }}"
    - name: "üêß Upload Linux version to itch.io"
      if: ${{ steps.release.outputs.version != '' }}
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: hypnagonia
        ITCH_USER: dbzer0
        PACKAGE: Hypnagonia_Linux.x86_64
        VERSION: "${{ steps.release.outputs.version }}"
    - name: "‚ò£ Upload OSX version to itch.io"
      if: ${{ steps.release.outputs.version != '' }}
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: osx
        ITCH_GAME: hypnagonia
        ITCH_USER: dbzer0
        PACKAGE: Hypnagonia_MacOSX.zip
        VERSION: "${{ steps.release.outputs.version }}"
    - name: üì® Notify Matrix General Chat
      uses: s3krit/matrix-message-action@v0.0.3
      with:
        room_id: ${{ secrets.MATRIX_ROOM_ID }}
        access_token: ${{ secrets.MATRIX_TOKEN }}
        message: "New Release Available: [${{ steps.release.outputs.version }}](https://github.com/db0/hypnagonia/blob/main/CHANGELOG.md)"
        server: "matrix.org"
      if: ${{ steps.release.outputs.version != '' }}
